services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod 
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db  
  db:
    container_name: postgresdb
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - 5432:5432
volumes:
  postgres_data:
    external: true
    name: postgres_data
